<?php
/** @package Ercco::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PermissaoMap.php");

/**
 * PermissaoDAO provides object-oriented access to the permissao table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Ercco::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PermissaoDAO extends Phreezable
{
	/** @var int */
	public $IdPermissao;

	/** @var string */
	public $Visualizar;

	/** @var string */
	public $Editar;

	/** @var string */
	public $Criar;

	/** @var string */
	public $Excluir;


	/**
	 * Returns a dataset of RelGrupoPermissaoMenu objects with matching Permissao
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetRelGrupoPermissaoMenus($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_perm_rel_grp_per_menu", $criteria);
	}


}
?>