<?php
/** @package Ercco::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PlataformaMap.php");

/**
 * PlataformaDAO provides object-oriented access to the plataforma table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Ercco::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PlataformaDAO extends Phreezable
{
	/** @var int */
	public $IdPlataforma;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Versao;


	/**
	 * Returns a dataset of Dispositivo objects with matching IdPlataforma
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdDispositivos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_plataforma_dispoistivo", $criteria);
	}


}
?>