<?php
/** @package Ercco::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("RelGrupoPermissaoMenuMap.php");

/**
 * RelGrupoPermissaoMenuDAO provides object-oriented access to the rel_grupo_permissao_menu table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Ercco::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class RelGrupoPermissaoMenuDAO extends Phreezable
{
	/** @var char */
	public $RelGrupoPermissaoMenu;

	/** @var int */
	public $Permissao;

	/** @var int */
	public $Grupo;

	/** @var int */
	public $Menu;


	/**
	 * Returns the foreign object based on the value of Grupo
	 * @return Grupo
	 */
	public function GetGrupo()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_grp_rel_grp_per_menu");
	}

	/**
	 * Returns the foreign object based on the value of Menu
	 * @return Menu
	 */
	public function GetMenu()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_menu_rel_grp_per_menu");
	}

	/**
	 * Returns the foreign object based on the value of Permissao
	 * @return Permissao
	 */
	public function GetPermissao()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_perm_rel_grp_per_menu");
	}


}
?>