<?php
/** @package Ercco::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("RelUsuarioGrupoMap.php");

/**
 * RelUsuarioGrupoDAO provides object-oriented access to the rel_usuario_grupo table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Ercco::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class RelUsuarioGrupoDAO extends Phreezable
{
	/** @var int */
	public $RelUsuarioGrupo;

	/** @var int */
	public $Usuario;

	/** @var int */
	public $Grupo;


	/**
	 * Returns the foreign object based on the value of Grupo
	 * @return Grupo
	 */
	public function GetGrupo()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_grupo_rel_usuario_grupo");
	}

	/**
	 * Returns the foreign object based on the value of Usuario
	 * @return Usuario
	 */
	public function GetUsuario()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_usuario_rel_usuario_grupo");
	}


}
?>